{% set name = "pyzipper" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyzipper-{{ version }}.tar.gz
  sha256: a4b96afcac04c5589d5abdc6158dd362166374e3cc6810aa441e65f8a17cb9e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pycryptodomex

test:
  imports:
    - pyzipper
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/danifus/pyzipper
  summary: AES encryption for zipfile.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
